### ISSUE TITLE
Docker version issue

### ISSUE THREAD

**Issue by tuxpeople** [puzzle/ansible-rancher#25]
Hi There

Sorry to bother you again. In the official Docker repo, used by the Docker role, the newest Docker version is 20.10.1. Which causes an unsupported Docker version error later in rke. 

I worked around with fixing the version in group_vars:
```
# grep docker inventories/group_vars/all.yml
docker_package: docker-ce-19.03.13
```

That's not a perfect solution, but I'm not sure what a good solution would be. I see the following possibilities:

- Adding a version variable (One could think of a variable to set on `19.03` which then uses yum to search for the newest `19.03` release
- Make use of the Docker script of Rancherlabs (`curl https://releases.rancher.com/install-docker/19.03.sh | sh`) which is again not a perfect solution as it would run every time

What do you think?

BR
Thomas

**Comment by PhilipSchmid** [comment]
Hi Thomas,

Thanks for reporting this issue and your thoughts about it.

Without having a detailed look at the issue, I think I would try to add a group_var which allows someone to specify the Rancher Docker installation script supported Docker version (https://github.com/rancher/install-docker) which then is used to download and run the `https://releases.rancher.com/install-docker/*` script. I think it should be possible to add a corresponding condition to the "Docker script of Rancherlabs" task which causes it to only run then the wished Docker version is not already present on the host system.

What do you think about that?

Thanks & regards,
Philip

**Comment by tuxpeople** [comment]
That's gonna work, yep. One could think of setting a custom fact based on `docker version --format '{{.Server.Version}}'`

**Comment by PhilipSchmid** [comment]
Hi @tuxpeople,

I just merged the PR so you would be able to further improve the logic with a custom fact based on `docker version --format '{{.Server.Version}}'` (via fork from the master branch).

Thanks & regards,
Philip
